In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
table = np.array([[1,3],[2,4]])
print(table.max(axis=1))

[3 4]


In [35]:
age = np.random.randint(25,45,50)
age

array([39, 30, 33, 35, 32, 26, 26, 34, 38, 30, 38, 38, 29, 35, 31, 29, 28,
       35, 36, 43, 26, 36, 28, 29, 30, 26, 36, 35, 34, 25, 26, 43, 38, 37,
       33, 25, 34, 33, 42, 31, 25, 35, 34, 39, 43, 34, 34, 36, 33, 43])

In [27]:
age[0:2]=-1
age[2:4]= 99
print(age)

[-1 -1 99 99 39 41 25 33 41 28 33 26 37 37 44 37 35 37 33 42 32 33 43 38
 38 30 27 30 34 39 38 43 37 39 43 40 42 40 25 36 44 33 25 41 37 32 30 29
 28 39]


In [36]:
plt.hist(age,bins=50)
plt.show()

In [34]:
plt.boxplot(age)
plt.show()

In [10]:
age[age<25]

array([-1, -1])

In [11]:
age[age>50]

array([99, 99])

In [12]:
for i in range(len(age)):
    if age[i] < 25:
        print(age[i])

-1
-1


In [13]:
age>50

array([False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [14]:
age

array([-1, -1, 99, 99, 42, 33, 32, 31, 25, 37, 34, 33, 34, 41, 32, 30, 37,
       29, 43, 25, 44, 26, 40, 42, 43, 38, 38, 39, 31, 37, 41, 44, 41, 28,
       41, 38, 30, 27, 34, 41, 30, 36, 25, 42, 34, 27, 25, 40, 32, 38])

In [16]:
age[age>50 ] = age.mean()
age

array([-1, -1, 36, 36, 42, 33, 32, 31, 25, 37, 34, 33, 34, 41, 32, 30, 37,
       29, 43, 25, 44, 26, 40, 42, 43, 38, 38, 39, 31, 37, 41, 44, 41, 28,
       41, 38, 30, 27, 34, 41, 30, 36, 25, 42, 34, 27, 25, 40, 32, 38])

In [17]:
age[age<20 ] = age.mean()

In [37]:
age[(age<25) | (age>50)] =age.mean()
age

array([39, 30, 33, 35, 32, 26, 26, 34, 38, 30, 38, 38, 29, 35, 31, 29, 28,
       35, 36, 43, 26, 36, 28, 29, 30, 26, 36, 35, 34, 25, 26, 43, 38, 37,
       33, 25, 34, 33, 42, 31, 25, 35, 34, 39, 43, 34, 34, 36, 33, 43])

In [21]:
sorted([2,3,6,21,564,73,124,3,4])

[2, 3, 3, 4, 6, 21, 73, 124, 564]

In [23]:
age.sort()
age

array([25, 25, 25, 25, 26, 27, 27, 28, 29, 30, 30, 30, 31, 31, 32, 32, 32,
       33, 33, 33, 33, 34, 34, 34, 34, 36, 36, 36, 37, 37, 37, 38, 38, 38,
       38, 39, 40, 40, 41, 41, 41, 41, 41, 42, 42, 42, 43, 43, 44, 44])

In [24]:
age[::-1]

array([44, 44, 43, 43, 42, 42, 42, 41, 41, 41, 41, 41, 40, 40, 39, 38, 38,
       38, 38, 37, 37, 37, 36, 36, 36, 34, 34, 34, 34, 33, 33, 33, 33, 32,
       32, 32, 31, 31, 30, 30, 30, 29, 28, 27, 27, 26, 25, 25, 25, 25])

In [26]:
age.sort()
age

TypeError: 'reversed' is an invalid keyword argument for sort()

In [31]:
# np.array([1,2,3,4,5,6])

In [32]:
serr = pd.Series([11,12,13,14,52,31,34,21])
serr

0    11
1    12
2    13
3    14
4    52
5    31
6    34
7    21
dtype: int64

In [34]:
type(serr)

pandas.core.series.Series

In [35]:
serr.size

8

In [37]:
len(serr)

8

In [38]:
serr.ndim

1

In [41]:
serr.values

array([11, 12, 13, 14, 52, 31, 34, 21], dtype=int64)

In [42]:
[i for i in serr.values]

[11, 12, 13, 14, 52, 31, 34, 21]

In [45]:
serr = pd.Series([11,12,13,14,52,31,34,21,13,14,6,57,4,36,2,6,52,31,34,21])
serr

0     11
1     12
2     13
3     14
4     52
5     31
6     34
7     21
8     13
9     14
10     6
11    57
12     4
13    36
14     2
15     6
16    52
17    31
18    34
19    21
dtype: int64

In [46]:
serr.head(10)

0    11
1    12
2    13
3    14
4    52
5    31
6    34
7    21
8    13
9    14
dtype: int64

In [48]:
serr.T

TypeError: 'Series' object is not callable

In [49]:
conda list

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2021.05                  py38_0  
anaconda-client           1.7.2                    py38_0  
anaconda-navigator        2.0.3                    py38_0  
anaconda-project          0.9.1              pyhd3eb1b0_1  
anyio                     2.2.0            py38haa95532_2  
appdirs                   1.4.4                      py_0  
argh                      0.26.2                   py38_0  
argon2-cffi               20.1.0           py38h2bbff1b_1  
asn1crypto                1.4.0                      py_0  
astroid                   2.5              py38haa95532_1  
astropy                   4.2.1            py38h2bbff1b_1  
async_generator           1.10               pyhd3eb1b0_0  
atomicwrites              1.4.0     

In [50]:
serr.tail(4)

16    52
17    31
18    34
19    21
dtype: int64

In [51]:
pd.Series(list('clarusway'))

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [54]:
data = [ 'paris','ist','astana']
index = ['x','y','z']

pd.Series(data,index)
pd.Series([ 'paris','ist','astana'], ['x','y','z'])

x     paris
y       ist
z    astana
dtype: object

In [53]:
conda install -c conda-forge jupyterlab

^C

Note: you may need to restart the kernel to use updated packages.


In [57]:
json.__doc__


NameError: name 'json' is not defined

In [61]:
dic = {'d':10 , 'c':24}
pd.Series()

0    Automatically created module for IPython inter...
dtype: object

In [62]:
ser1 = pd.Series([1,2,3,4], index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4], index = ['USA', 'Germany','Italy', 'Japan'])

In [64]:
ser1.index


Index(['USA', 'Germany', 'USSR', 'Japan'], dtype='object')

In [65]:
ser1.values

array([1, 2, 3, 4], dtype=int64)

In [67]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [69]:
ser1.sort_values()

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [70]:
ser1['Germany']

2

In [71]:
ser1[ser1==1]

USA    1
dtype: int64

In [73]:
ser1[['Japan','Germany']]

Japan      4
Germany    2
dtype: int64

In [75]:
ser1.Japan

4

In [79]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [80]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [1]:
import pandas as pd

In [2]:
panser = pd.Series(data =[121,200,150,99,145,120,180], 
                   index=['terry', 'micheal','orion','jason','adam','thomas','zack'])
panser

terry      121
micheal    200
orion      150
jason       99
adam       145
thomas     120
zack       180
dtype: int64

In [3]:
panser.jason

99

In [5]:
panser['jason']

99

In [6]:
panser[['orion','adam']]

orion    150
adam     145
dtype: int64

In [7]:
panser['orion':'adam']

orion    150
jason     99
adam     145
dtype: int64

In [9]:
panser[2:5]

orion    150
jason     99
adam     145
dtype: int64

In [17]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason', 'adam', 'thomas', 'zack'], dtype='object')

In [11]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason', 'adam', 'thomas', 'zack'], dtype='object')

In [12]:
panser.values

array([121, 200, 150,  99, 145, 120, 180], dtype=int64)

In [38]:
(panser.values)[3]

99

In [16]:
panser.items()

In [46]:
panser.is_unique

True

In [47]:
panser.drop('terry')

micheal    200
orion      150
jason       99
adam       145
thomas     120
zack       180
dtype: int64

In [48]:
panser

terry      121
micheal    200
orion      150
jason       99
adam       145
thomas     120
zack       180
dtype: int64

In [49]:
list(panser.items())

[('terry', 121),
 ('micheal', 200),
 ('orion', 150),
 ('jason', 99),
 ('adam', 145),
 ('thomas', 120),
 ('zack', 180)]

In [50]:
for key,value in panser.items():
    print("key:",key, "\t value:",value)

key: terry 	 value: 121
key: micheal 	 value: 200
key: orion 	 value: 150
key: jason 	 value: 99
key: adam 	 value: 145
key: thomas 	 value: 120
key: zack 	 value: 180


In [51]:
'adam' in panser

True

In [53]:
121 in panser

False

In [54]:
121 in panser.valuesb

True

In [56]:
panser.isin([121,99])

terry       True
micheal    False
orion      False
jason       True
adam       False
thomas     False
zack       False
dtype: bool

In [57]:
panser

terry      121
micheal    200
orion      150
jason       99
adam       145
thomas     120
zack       180
dtype: int64

In [58]:
panser.jason = 190
panser

terry      121
micheal    200
orion      150
jason      190
adam       145
thomas     120
zack       180
dtype: int64

In [59]:
panser>=180

terry      False
micheal     True
orion      False
jason       True
adam       False
thomas     False
zack        True
dtype: bool

In [60]:
panser[panser>=180]

micheal    200
jason      190
zack       180
dtype: int64

In [62]:
panser[panser>=180] = 155
panser

terry      121
micheal    155
orion      150
jason      155
adam       145
thomas     120
zack       155
dtype: int64