___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [3]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [4]:
my_list=np.array([5,10,15,20,25])
my_list

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [8]:
np.ones((4,4),dtype='int')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

In [5]:
np.full((4,4),7,dtype='int')

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [6]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [35]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [9]:
np.linspace(0,25,25,dtype='int', endpoint=False).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 25]])

#### 10. Create 5 random number with numpy

In [44]:
np.random.rand(5)

array([0.12226323, 0.44279066, 0.14035038, 0.05066587, 0.94211782])

#### 11. Create random normal distributed 5x5 array

In [6]:
np.random.randn(5,5)

array([[ 1.07921333, -0.6646672 ,  0.35907252,  0.14618663, -0.71093989],
       [-0.69981354,  0.36339115, -1.67556938,  0.93978312, -1.00910844],
       [-0.43732785, -0.07065423,  0.17378852,  2.22657631, -1.85238911],
       [ 1.48506675,  1.20810692, -0.65663697,  0.51046214,  0.17457907],
       [ 0.07791189, -1.30259495,  0.72766804, -0.13946347,  0.7011086 ]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [9]:
np.random.randint(20,50,size=(3,4))

array([[24, 40, 48, 45],
       [31, 39, 42, 43],
       [30, 23, 22, 46]])

array([[34, 23, 41, 29],
       [37, 47, 45, 49],
       [37, 25, 44, 29]])

#### 13. Reshape the array below with shape 6x8

In [10]:
ranarr = np.random.randint(0, 60, 48)
ranarr.reshape(6,8)

array([[54,  5, 50, 42, 46,  2,  9, 37],
       [ 3, 17, 36, 55, 21, 36, 15, 35],
       [18, 27,  7, 26, 45, 33, 28, 19],
       [ 0, 29,  8, 15, 46, 20,  7, 19],
       [12, 55, 28, 34, 11, 17, 37, 33],
       [45, 43, 52,  0, 19, 40, 34, 10]])

In [91]:
ranarr = np.random.randint(0, 60, 48)

array([31, 17, 58,  3, 11, 19, 12, 35, 28, 18, 52, 24, 41, 40, 14, 56, 48,
        8, 15,  7, 45,  3,  1, 56, 40, 53, 13, 29, 33,  2, 45, 46, 53, 19,
       33, 21, 37, 52, 41, 25, 54, 52,  3,  7, 36, 30, 37, 42])

array([[31, 17, 58,  3, 11, 19, 12, 35],
       [28, 18, 52, 24, 41, 40, 14, 56],
       [48,  8, 15,  7, 45,  3,  1, 56],
       [40, 53, 13, 29, 33,  2, 45, 46],
       [53, 19, 33, 21, 37, 52, 41, 25],
       [54, 52,  3,  7, 36, 30, 37, 42]])

In [12]:
#reshape with -1
ranarr = np.random.randint(0, 60, 48)
ranarr.reshape(6,-1)

array([[12, 50, 39, 42, 29, 27,  5, 36],
       [55, 43, 14, 34, 30,  5, 40,  1],
       [34, 20, 52,  4,  7, 21, 14, 15],
       [37, 41, 10, 10, 57, 11, 13, 41],
       [50, 28, 59, 27, 53,  2, 55,  0],
       [37, 19, 19, 25, 59, 43, 58, 47]])

## Numpy Indexing and Selection


In [13]:
#Create array below
sl = np.arange(1,17).reshape(4,4)
sl

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [26]:
sl[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [28]:
sl[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [14]:
sl[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [23]:
sl[:,2] =77
sl

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [40]:
sl[[1,3],[0,2]]

array([ 5, 77])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [15]:
sl[1::2,0::2]

array([[ 5,  7],
       [13, 15]])

In [14]:
sl[2:4:2,1:4:2]

array([[10, 12]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [24]:
sl

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [17]:
sl[sl<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
sum_sl = sl[(sl<10)] + sl[(sl>12)]
sum_sl

array([78, 79, 81, 18, 20, 85, 25])

In [25]:
sl[sl>12]

array([77, 77, 77, 13, 14, 77, 16])

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [24]:
np.std(sum_sl)

29.700546274093877

#### 22. Get the sum of second column from array above

In [25]:
#print array here
sl

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [28]:
sl[:,1].sum()

32

In [26]:
sum(sl[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [30]:
#median
np.median(sl[2])

11.0

In [31]:
sl[2].mean()

27.0

In [32]:
sl[2]

array([ 9, 10, 77, 12])

In [118]:
#mean


10.5

In [36]:
sl[:,3].std()

4.47213595499958

In [119]:
#std

1.118033988749895

# Pandas Section

In [2]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [3]:

df1 = pd.read_csv( 'salaries.csv')
df1.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [33]:
pwd

'c:\\Users\\yasir\\Desktop\\clarusway GİTHUB\\python-project\\DS_projects\\DS Assignments'

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [14]:
df1.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year value are there**

In [38]:
df1.Year.value_counts(dropna = False)

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [17]:
df1.nunique()

Id                  148654
EmployeeName        110811
JobTitle              2159
BasePay             109489
OvertimePay          65998
OtherPay             83225
Benefits             98465
TotalPay            138486
TotalPayBenefits    142098
Year                     4
Notes                    0
Agency                   1
Status                   0
dtype: int64

**Print out max and avg Totalpay**

In [18]:
df1.TotalPay.max()

567595.43

In [132]:
#max

567595.43

In [21]:
df1.TotalPay.mean()

74768.321971703

In [133]:
#avg

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [48]:
df1.loc[:,'TotalPay'][(df1.TotalPay)>(df1.TotalPay.mean())].count()

69489

In [39]:
df1[df1.TotalPay>df1.mean()]

In [ ]:
len(df1[df1.TotalPay>df1.mean()])

**How much does ALBERT PARDINI make (including benefits)?**

In [4]:
df1[df1.EmployeeName == 'ALBERT PARDINI']['TotalPayBenefits']

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [52]:
df1.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [27]:
df1.benefits

AttributeError: 'DataFrame' object has no attribute 'benefits'

In [86]:
var1 = 'ALBERT PARDINI'
df1[df1.eq(var1).any(1)]['TotalPayBenefits']

2    335279.91
Name: TotalPayBenefits, dtype: float64

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [30]:
df1[['EmployeeName']]

EmployeeName
0          NATHANIEL FORD
1            GARY JIMENEZ
2          ALBERT PARDINI
3       CHRISTOPHER CHONG
4         PATRICK GARDNER
...                   ...
148649      Roy I Tillery
148650       Not provided
148651       Not provided
148652       Not provided
148653          Joe Lopez

[148654 rows x 1 columns]

In [31]:
df1[['EmployeeName','TotalPay']].min()

EmployeeName    A BERNARD FATOOH
TotalPay                 -618.13
dtype: object

In [17]:
df1['TotalPay'].min()

-618.13

**Who is lowest paid person**

In [6]:
df1[df1.TotalPayBenefits==df1.TotalPayBenefits.min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [93]:
df1['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [41]:
df1.JobTitle.value_counts().tail(3)

COURT CLERK                    1
Asst Chf Prob Ofc, Juv Prob    1
DIRECTOR, JUVENILE HALL        1
Name: JobTitle, dtype: int64

In [ ]:
df1.JobTitle.sum()

LEGISLATION CLERK                    1
Sheriff                              1
MATERIALS AND SUPPLIES SUPERVISOR    1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [7]:
df1.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [11]:
len(df1[(df1.TotalPayBenefits > (df1.TotalPayBenefits.mean())) & (df1.Year == 2012)])

20366

In [ ]:
df1[(df1['EmployeeName']) > ]

20366

**How many people have the word Manager in their job title?**

In [12]:
#use apply function here
df1[df1.JobTitle.apply(lambda x : True if 'manager' in x.lower() else False)]

Id          EmployeeName  \
0            1        NATHANIEL FORD   
83          84        EDWARD REISKIN   
87          88           KEVIN BARRY   
95          96          MIVIC HIROSE   
162        163         JULIE LABONTE   
...        ...                   ...   
147216  147217  Steven D Koneffklatt   
147502  147503    Alice B Villagomez   
147805  147806    Stephen C Laplante   
148150  148151      Shirley M Parker   
148475  148476         James P Horan   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
83      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  230827.12   
87                                         MANAGER VII   96814.36   
95                                        MANAGER VIII  215180.76   
162                                       MANAGER VIII  207501.20   
...                                                ...        ...   
147216                                     Manager III       0.00   
147502                                      Manager IV    1660.00   
147805                                      Manager II       0.00   
148150                           Real Property Manager       0.00   
148475                                      Manager IV     175.75   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0               0.0  400184.25       NaN  567595.43         567595.43  2011   
83              0.0       0.00       NaN  230827.12         230827.12  2011   
87              0.0  133563.47       NaN  230377.83         230377.83  2011   
95              0.0   12000.00       NaN  227180.76         227180.76  2011   
162             0.0    2903.37       NaN  210404.57         210404.57  2011   
...             ...        ...       ...        ...               ...   ...   
147216          0.0    1890.72    342.03    1890.72           2232.75  2014   
147502          0.0       0.00     16.60    1660.00           1676.60  2014   
147805          0.0     982.62    177.76     982.62           1160.38  2014   
148150          0.0     647.76      0.00     647.76            647.76  2014   
148475          0.0       0.00      1.41     175.75            177.16  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
83        NaN  San Francisco     NaN  
87        NaN  San Francisco     NaN  
95        NaN  San Francisco     NaN  
162       NaN  San Francisco     NaN  
...       ...            ...     ...  
147216    NaN  San Francisco     NaN  
147502    NaN  San Francisco     NaN  
147805    NaN  San Francisco     NaN  
148150    NaN  San Francisco     NaN  
148475    NaN  San Francisco     NaN  

[4110 rows x 13 columns]

In [13]:
len(df1[df1.JobTitle.apply(lambda x : True if 'manager' in x.lower() else False)])

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [14]:
sal_new = df1.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [16]:
sal_new = sal_new.loc[:,'EmployeeName':'TotalPayBenefits']
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [17]:
df1[(df1.TotalPayBenefits > df1.TotalPayBenefits.min()) & (df1.TotalPayBenefits < df1.TotalPayBenefits.mean()) ]['EmployeeName']

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object