# Mentoring-1

### NUMPY

In [ ]:
4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.Go to the editor
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [3]:
import numpy as np
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a[6] = 11
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [ ]:
8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. Go to the editor
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [10]:
import numpy as np
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
a[1:4]=0
a

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [11]:
a[1:4,1:4] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# 2. yöntem :
a[1:4,1:4]-1.0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#slicing ile copy arasındaki fark:

In [13]:
import numpy as np
a = np.ones((5,5))
b = a[1:4,1:4]
b[1:2,1:2] = 0
b

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [14]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
import numpy as np
a = np.ones((5,5))
b = a.copy()
b[1:4,1:4] = 0
b

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# numpy mathematics cheatsheet

In [ ]:
9. Write a NumPy program to add a border (filled with 0's) around an existing array. Go to the editor
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
...........
[ 0. 0. 0. 0. 0.]]

In [24]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
a = np.pad(a, pad_width=2, mode='constant', constant_values=5)
a

array([[5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 1., 1., 1., 5., 5.],
       [5., 5., 1., 1., 1., 5., 5.],
       [5., 5., 1., 1., 1., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.]])

In [18]:
? np.pad

Signature:  np.pad(array, pad_width, mode='constant', **kwargs)
Docstring:
Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        ve

In [19]:
a = [1, 2, 3, 4, 5]
print(a)
np.pad(a, (2, 3), 'constant', constant_values=(4, 6))

[1, 2, 3, 4, 5]


array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [10]:
np.pad(a, (2, 3), 'edge')


array([1, 1, 1, 2, 3, 4, 5, 5, 5, 5])

In [11]:
np.pad(a, (2, 3), 'linear_ramp', end_values=(5, -4))

array([ 5,  3,  1,  2,  3,  4,  5,  2, -1, -4])

In [12]:
np.pad(a, (2,), 'maximum')

array([5, 5, 1, 2, 3, 4, 5, 5, 5])

In [ ]:
10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern. Go to the editor
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [26]:
a = np.zeros((8,8))
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
a[1::2,::2] = 1
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [28]:
a[::2,1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
12. Write a NumPy program to append values to the end of an array. Go to the editor
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [34]:
import numpy as np
a = np.arange(10,40,10)
a

array([10, 20, 30])

In [35]:
b = np.arange(40,70,10)
b

array([40, 50, 60])

In [36]:
c = np.arange(70,100,10)
c

array([70, 80, 90])

In [38]:
d = np.append(a,[b,c])
d

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
e = np.append(a, [[40, 50, 60], [70, 80, 90]])
e

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. Go to the editor
Sample Array [0, 12, 45.21 ,34, 99.91]
Expected Output:
Values in Fahrenheit degrees:
[ 0. 12. 45.21 34. 99.91]
Values in Centigrade degrees:
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [12]:
import numpy as np
Fahr = np.array([0, 12, 45.21 ,34, 99.91])
Cent = np.subtract(Fahr,32)
Cent = np.multiply(Cent,5)
Cent = np.divide(Cent,9)
Cent

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])

In [13]:
#2.yöntem
import numpy as np

F = np.array([0, 12, 45.21, 34, 99.91])
print(5*F/9 - 5*32/9)


[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [ ]:
19. Write a NumPy program to get the unique elements of an array. Go to the editor
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]

In [43]:
import numpy as np
a = np.array([10, 10, 20, 20, 30, 30])
print(np.unique(a))
print(a)

[10 20 30]
[10 10 20 20 30 30]


In [57]:
a = np.array([[1, 1], [2, 3]])
a

array([[1, 1],
       [2, 3]])

In [58]:
print(np.unique(a))

[1 2 3]


In [62]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a[0:1,1:3]=5
print(a)
print(np.unique(a))

[[1 5 5]
 [4 5 6]
 [7 8 9]]
[1 4 5 6 7 8 9]


In [68]:
# method ile func arasındaki fark
import numpy as np
a = np.array([10,20,40,40,50,30,30,10])
print(np.sort(a))
print(a)

[10 10 20 30 30 40 40 50]
[10 20 40 40 50 30 30 10]


In [71]:
a.sort()
a

array([10, 10, 20, 30, 30, 40, 40, 50])

In [72]:
print(a)

[10 10 20 30 30 40 40 50]


### PANDAS