In [2]:
%config IPCompleter.greedy=True
!pip install ipython --upgrade
!pip install jedi
!pip3 install jupyter-tabnine
!jupyter nbextension install --py jupyter_tabnine
!jupyter nbextension enable --py jupyter_tabnine
!jupyter serverextension enable --py jupyter_tabnine

  Using cached ipython-7.28.0-py3-none-any.whl (788 kB)
  Attempting uninstall: ipython
    Found existing installation: ipython 7.22.0
    Uninstalling ipython-7.22.0:


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\ipython-7.22.0.dist-info\\direct_url.json'
Consider using the `--user` option or check the permissions.



Installing C:\ProgramData\Anaconda3\lib\site-packages\jupyter_tabnine\static -> jupyter_tabnine
Up to date: C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\main.css
Up to date: C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\main.js
Up to date: C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\README.md
Up to date: C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\tabnine.yaml
- Validating: ok

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable jupyter_tabnine --py
    
Enabling notebook extension jupyter_tabnine/main...
      - Validating: ok
Enabling: jupyter_tabnine
- Writing config: C:\Users\yasir\.jupyter
    - Validating...
      jupyter_tabnine  ok


In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data = [1,3,5,6,7,8,9]
data

[1, 3, 5, 6, 7, 8, 9]

In [5]:
pd.DataFrame(data, columns=['col1'])

col1
0     1
1     3
2     5
3     6
4     7
5     8
6     9

In [6]:
pd.Series(data)

0    1
1    3
2    5
3    6
4    7
5    8
6    9
dtype: int64

In [7]:
data2 = np.arange(1,24,2).reshape(3,4)
data2

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [8]:
pd.DataFrame(data2, columns=['col1','col2','col3','col4']) 

col1  col2  col3  col4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [9]:
df = pd.DataFrame(data2, columns=['col1','col2','col3','col4'],index=['a','b','c']) 
df

col1  col2  col3  col4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.size

12

In [12]:
df.ndim

2

In [13]:
df.shape

(3, 4)

In [14]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [15]:
df.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [16]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [17]:
len(df)

3

In [18]:
df.keys()

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [19]:
df.mean()

col1     9.0
col2    11.0
col3    13.0
col4    15.0
dtype: float64

In [20]:
df.col1

a     1
b     9
c    17
Name: col1, dtype: int32

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      int32
 1   col2    3 non-null      int32
 2   col3    3 non-null      int32
 3   col4    3 non-null      int32
dtypes: int32(4)
memory usage: 180.0+ bytes


In [22]:
df.size

12

In [23]:
df.describe()

col1  col2  col3  col4
count   3.0   3.0   3.0   3.0
mean    9.0  11.0  13.0  15.0
std     8.0   8.0   8.0   8.0
min     1.0   3.0   5.0   7.0
25%     5.0   7.0   9.0  11.0
50%     9.0  11.0  13.0  15.0
75%    13.0  15.0  17.0  19.0
max    17.0  19.0  21.0  23.0

In [24]:
df.value_counts()

col1  col2  col3  col4
1     3     5     7       1
9     11    13    15      1
17    19    21    23      1
dtype: int64

In [25]:
df.sum()

col1    27
col2    33
col3    39
col4    45
dtype: int64

In [26]:
df.nunique()

col1    3
col2    3
col3    3
col4    3
dtype: int64

In [27]:
s1 = np.random.randint(2,10, size = 40)
s2 = np.random.randint(30,100, size = 40)
s3 = np.random.randint(100,150, size = 40)

In [28]:
myDict = {'var1':s1,'var2':s2,'var3':s3}
myDict

{'var1': array([7, 2, 9, 4, 9, 9, 3, 6, 8, 3, 4, 6, 9, 4, 6, 3, 6, 2, 5, 2, 8, 8,
        5, 5, 4, 2, 5, 3, 9, 2, 2, 6, 9, 8, 4, 9, 7, 4, 9, 4]),
 'var2': array([30, 74, 57, 53, 44, 86, 44, 47, 73, 78, 82, 90, 72, 62, 77, 76, 92,
        82, 80, 64, 37, 43, 45, 64, 95, 77, 53, 48, 95, 85, 61, 33, 58, 84,
        95, 31, 59, 85, 31, 37]),
 'var3': array([112, 128, 130, 144, 101, 120, 119, 115, 112, 103, 126, 131, 140,
        104, 112, 114, 104, 105, 132, 100, 148, 120, 111, 122, 124, 131,
        126, 147, 100, 136, 116, 123, 123, 106, 129, 125, 137, 143, 130,
        100])}

In [29]:
df_dict = pd.DataFrame(myDict)
df_dict

var1  var2  var3
0      7    30   112
1      2    74   128
2      9    57   130
3      4    53   144
4      9    44   101
5      9    86   120
6      3    44   119
7      6    47   115
8      8    73   112
9      3    78   103
10     4    82   126
11     6    90   131
12     9    72   140
13     4    62   104
14     6    77   112
15     3    76   114
16     6    92   104
17     2    82   105
18     5    80   132
19     2    64   100
20     8    37   148
21     8    43   120
22     5    45   111
23     5    64   122
24     4    95   124
25     2    77   131
26     5    53   126
27     3    48   147
28     9    95   100
29     2    85   136
30     2    61   116
31     6    33   123
32     9    58   123
33     8    84   106
34     4    95   129
35     9    31   125
36     7    59   137
37     4    85   143
38     9    31   130
39     4    37   100

In [30]:
df_dict[3:5]

var1  var2  var3
3     4    53   144
4     9    44   101

In [31]:
df_dict2 = df_dict[3:5]
df_dict2

var1  var2  var3
3     4    53   144
4     9    44   101

In [32]:
df_dict2.index = ['a','b']
df_dict2

var1  var2  var3
a     4    53   144
b     9    44   101

In [33]:
df_dict2.columns = ['X','Y','Z']

In [34]:
df_dict2

X   Y    Z
a  4  53  144
b  9  44  101

In [35]:
pd.DataFrame(df_dict2.values, index=[],columns=[])

ValueError: Shape of passed values is (2, 3), indices imply (0, 0)

In [ ]:
np.random.randn(5,4)

array([[ 1.0283112 ,  0.08304729, -1.25289438,  0.04601786],
       [ 0.08195481,  0.96978283, -0.32538689, -0.62539582],
       [ 0.61799029, -0.21107962,  1.54586619,  2.04703677],
       [-0.61313579, -0.33468073,  0.34483703,  0.11866374],
       [-0.89905043, -1.52456242,  0.87491481, -0.07541444]])

In [36]:
np.random.seed(101)
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [ ]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [4]:
np.random.seed(101)

In [5]:

df3 = pd.DataFrame(np.random.rand(5,4),
                   index= 'A B C D E'.split(),
                   columns= 'W X Y Z'.split())
df3

W         X         Y         Z
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [7]:
df3['W']

A    0.516399
B    0.685277
C    0.721544
D    0.181892
E    0.083561
Name: W, dtype: float64

In [8]:
df3.W

A    0.516399
B    0.685277
C    0.721544
D    0.181892
E    0.083561
Name: W, dtype: float64

In [9]:
df3[['W']]

W
A  0.516399
B  0.685277
C  0.721544
D  0.181892
E  0.083561

In [10]:
df3[['W','Y']]

W         Y
A  0.516399  0.028474
B  0.685277  0.306966
C  0.721544  0.554228
D  0.181892  0.965483
E  0.083561  0.728993

In [12]:
df3.loc['B':'D','W':'Y']

W         X         Y
B  0.685277  0.833897  0.306966
C  0.721544  0.189939  0.554228
D  0.181892  0.785602  0.965483

In [13]:
df3['X'] + df3['Y']**2

A    0.571478
B    0.928125
C    0.497107
D    1.717760
E    1.134979
dtype: float64

In [15]:
df3['Result'] = df3['W']*df3['X'] + df3['Y']**2 - df3['Z']
df3

W         X         Y         Z    Result
A  0.516399  0.570668  0.028474  0.171522  0.123981
B  0.685277  0.833897  0.306966  0.893613 -0.227934
C  0.721544  0.189939  0.554228  0.352132  0.092086
D  0.181892  0.785602  0.965483  0.232354  0.842699
E  0.083561  0.603548  0.728993  0.276239  0.305625

In [23]:
df3['Result'] = df3['W']*df3['X'] + df3['Y'].std() - df3['Z'].mean()
df3

W         X         Y         Z    Result
A  0.516399  0.570668  0.028474  0.171522  0.273606
B  0.685277  0.833897  0.306966  0.893613  0.550365
C  0.721544  0.189939  0.554228  0.352132  0.115964
D  0.181892  0.785602  0.965483  0.232354  0.121810
E  0.083561  0.603548  0.728993  0.276239  0.029348

In [17]:
df3['Y'].std()

0.36408635555350793

In [25]:
df3.drop('Result',axis=1)

W         X         Y         Z
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [27]:
df3

W         X         Y         Z    Result
A  0.516399  0.570668  0.028474  0.171522  0.273606
B  0.685277  0.833897  0.306966  0.893613  0.550365
C  0.721544  0.189939  0.554228  0.352132  0.115964
D  0.181892  0.785602  0.965483  0.232354  0.121810
E  0.083561  0.603548  0.728993  0.276239  0.029348

In [28]:
## df3.drop('Result',axis=1, inplace=True)
df3 = df3.drop('Result',axis=1)
df3

W         X         Y         Z
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [32]:
df3.drop(['C','E'], axis= 0,inplace= True)
df3

KeyError: "['C' 'E'] not found in axis"

In [33]:
m=np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0    13    32    24     1
1    10     9    37    20
2    36    29     8    11
3    39    10    19     8
4    16     1    13    18
5    12    16    34    30
6    25    37    20    36
7    31    11    21    28

In [36]:
df4.loc[2]

var1    36
var2    29
var3     8
var4    11
Name: 2, dtype: int32

In [37]:
df4.loc[2:6]

var1  var2  var3  var4
2    36    29     8    11
3    39    10    19     8
4    16     1    13    18
5    12    16    34    30
6    25    37    20    36

In [38]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a    13    32    24     1
b    10     9    37    20
c    36    29     8    11
d    39    10    19     8
e    16     1    13    18
f    12    16    34    30
g    25    37    20    36
h    31    11    21    28

In [41]:
df4.loc["c"]

var1    36
var2    29
var3     8
var4    11
Name: c, dtype: int32

In [42]:
df4.loc['c':'f']

var1  var2  var3  var4
c    36    29     8    11
d    39    10    19     8
e    16     1    13    18
f    12    16    34    30

In [43]:
df4.loc['c':'f', 'var1':'var3']

var1  var2  var3
c    36    29     8
d    39    10    19
e    16     1    13
f    12    16    34

In [51]:
df4.loc['c':'f', 'var1':'var3'][::2]

var1  var2  var3
c    36    29     8
e    16     1    13

In [55]:
df4.loc['c':'f'][['var1','var3']]

var1  var3
c    36     8
d    39    19
e    16    13
f    12    34

In [50]:
df4.iloc[1:4,1:4]

var2  var3  var4
b     9    37    20
c    29     8    11
d    10    19     8

In [56]:
df4.iloc[1:4,2:4]

var3  var4
b    37    20
c     8    11
d    19     8

In [57]:
df3

W         X         Y         Z
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
D  0.181892  0.785602  0.965483  0.232354

In [58]:

df3 = pd.DataFrame(np.random.rand(5,4),
                   index= 'A B C D E'.split(),
                   columns= 'W X Y Z'.split())
df3

W         X         Y         Z
A  0.701371  0.487635  0.680678  0.521548
B  0.043397  0.223937  0.575205  0.120434
C  0.500117  0.138010  0.052808  0.178277
D  0.442368  0.877587  0.949264  0.478167
E  0.461119  0.637289  0.324608  0.117578

In [59]:
df3.iloc[:,2:]

Y         Z
A  0.680678  0.521548
B  0.575205  0.120434
C  0.052808  0.178277
D  0.949264  0.478167
E  0.324608  0.117578

In [60]:
df3.iloc[1,2:]

Y    0.575205
Z    0.120434
Name: B, dtype: float64

In [61]:
df3

W         X         Y         Z
A  0.701371  0.487635  0.680678  0.521548
B  0.043397  0.223937  0.575205  0.120434
C  0.500117  0.138010  0.052808  0.178277
D  0.442368  0.877587  0.949264  0.478167
E  0.461119  0.637289  0.324608  0.117578

In [64]:
df3["X"]>0

A    True
B    True
C    True
D    True
E    True
Name: X, dtype: bool

In [63]:
df3[df3["X"]>0]

W         X         Y         Z
A  0.701371  0.487635  0.680678  0.521548
B  0.043397  0.223937  0.575205  0.120434
C  0.500117  0.138010  0.052808  0.178277
D  0.442368  0.877587  0.949264  0.478167
E  0.461119  0.637289  0.324608  0.117578

In [67]:
df3[(df3["X"]>0) & (df3["Z"]>0)]

W         X         Y         Z
A  0.701371  0.487635  0.680678  0.521548
B  0.043397  0.223937  0.575205  0.120434
C  0.500117  0.138010  0.052808  0.178277
D  0.442368  0.877587  0.949264  0.478167
E  0.461119  0.637289  0.324608  0.117578

In [70]:
df3[(df3.X>0) & (df3.Z >0)]

W         X         Y         Z
A  0.701371  0.487635  0.680678  0.521548
B  0.043397  0.223937  0.575205  0.120434
C  0.500117  0.138010  0.052808  0.178277
D  0.442368  0.877587  0.949264  0.478167
E  0.461119  0.637289  0.324608  0.117578

In [73]:
df3[df3.Z>0]['W']

A    0.701371
B    0.043397
C    0.500117
D    0.442368
E    0.461119
Name: W, dtype: float64

In [75]:
df3[df3.Z>0][['W']]

W
A  0.701371
B  0.043397
C  0.500117
D  0.442368
E  0.461119

In [85]:
df3[df3.Z>0][['W']].iloc[2:5,:]

W
C  0.500117
D  0.442368
E  0.461119

In [81]:
df5=df3[df3.Z>0]
df5

W         X         Y         Z
A  0.701371  0.487635  0.680678  0.521548
B  0.043397  0.223937  0.575205  0.120434
C  0.500117  0.138010  0.052808  0.178277
D  0.442368  0.877587  0.949264  0.478167
E  0.461119  0.637289  0.324608  0.117578

In [89]:
df5.loc['B':'D']

W         X         Y         Z
B  0.043397  0.223937  0.575205  0.120434
C  0.500117  0.138010  0.052808  0.178277
D  0.442368  0.877587  0.949264  0.478167