In [4]:
import numpy as np


In [5]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
my_array_my_list = np.array(my_list)
my_array = np.array([6,7,8,9,0])
my_array

array([6, 7, 8, 9, 0])

In [8]:
my_array_my_list

array([1, 2, 3, 4, 5])

In [9]:
type(my_array)

numpy.ndarray

In [10]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [11]:
a+b

array([ 6,  8, 10, 12])

In [12]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [13]:
a.size

4

In [14]:
a.shape

(4,)

In [15]:
a.ndim

1

In [16]:
a.itemsize

4

In [17]:
a.dtype

dtype('int32')

In [18]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[2,3,4,5]])
b1 = np.array([[2,3,4,5],[1,2,4,5],[1,2,3,4]])

In [19]:
a1.size

12

In [20]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [23]:
b1

array([[2, 3, 4, 5],
       [1, 2, 4, 5],
       [1, 2, 3, 4]])

In [24]:
a1.shape

(3, 4)

In [25]:
a1.itemsize

4

In [26]:
a1*b1

array([[ 2,  6, 12, 20],
       [ 1,  4, 12, 20],
       [ 2,  6, 12, 20]])

In [29]:
a3 = np.array([[[1,2,3,4],[1,2,3,4],[2,3,4,5]],[[1,2,3,4],[1,2,3,4],[2,3,4,5]]])
a3

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 3, 4, 5]]])

In [31]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [32]:
np.arange(-4,6,3)

array([-4, -1,  2,  5])

In [33]:
my_list = [1,2.3,True,'ram',4,5]
my_list

[1, 2.3, True, 'ram', 4, 5]

In [35]:
arr=np.arange(-4,6,0.5)
arr

array([-4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,
        1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5])

In [50]:
np.linspace(25,45,5, dtype=int)

array([25, 30, 35, 40, 45])

In [55]:
np.zeros((5,3,2),dtype=str)

array([[['', ''],
        ['', ''],
        ['', '']],

       [['', ''],
        ['', ''],
        ['', '']],

       [['', ''],
        ['', ''],
        ['', '']],

       [['', ''],
        ['', ''],
        ['', '']],

       [['', ''],
        ['', ''],
        ['', '']]], dtype='<U1')

In [60]:
np.ones((2,4))/0

C:\Users\yasir\AppData\Local\Temp/ipykernel_4520/4236025466.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.ones((2,4))/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [61]:
np.full(4,'sonsuz')

array(['sonsuz', 'sonsuz', 'sonsuz', 'sonsuz'], dtype='<U6')

In [62]:
np.full((3,32,32),255)

array([[[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]]])

In [66]:
import matplotlib.pyplot as plt
%matplotlib inlinea = np.full((32,32,3), 255, dtype = int)
a[:,:,0] = 122 # red
a[:,:,1] = 20 # green
a[:,:,2] = 120 # blue
plt.imshow(a)

ModuleNotFoundError: No module named 'matplotlib'

In [68]:
b=np.arange(36)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [69]:
len(b)

36

In [70]:
b.size

36

In [71]:
b.shape

(36,)

In [77]:
b.reshape(12,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [78]:
b.max()

35

In [83]:
b.min()

0

In [84]:
c= np.array([2,3,56,2,1,6,36,3,4,16,7,34,])
c

array([ 2,  3, 56,  2,  1,  6, 36,  3,  4, 16,  7, 34])

In [85]:
c.max()

56

In [86]:
c.min()

1

In [87]:
c.size

12

In [88]:
c.shape


(12,)

In [89]:
c.argmin()

4

In [98]:
c.argmax() 


2

In [99]:
c.sum()

170