In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5,6,7,8]

In [3]:
a = np. array(my_list)

In [4]:
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
b = a[:3]
b

array([1, 2, 3])

In [7]:
b[0]= 88
b

array([88,  2,  3])

In [8]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [10]:
c = a.copy()
c[1] =22
c

array([88, 22,  3,  4,  5,  6,  7,  8])

In [11]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [12]:
type(c)

numpy.ndarray

In [13]:
a.shape

(8,)

In [14]:
a[-1]

8

In [15]:
a[::-1]

array([ 8,  7,  6,  5,  4,  3,  2, 88])

In [16]:
b = np.array([[1,2,3], [6,7,8]])
b

array([[1, 2, 3],
       [6, 7, 8]])

In [18]:
b[1,1] = 77
b

array([[ 1,  2,  3],
       [ 6, 77,  8]])

In [19]:
b.shape

(2, 3)

In [21]:
b[:,1] = 99
b

array([[ 1, 99,  3],
       [ 6, 99,  8]])

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [32]:
np.empty((3,3),dtype=int)

array([[-44943376,       564,         0],
       [  3801155,       684,         0],
       [      768,       564,   7536737]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.arange(5,60,4)

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57])

In [28]:
np.linspace(5,90,3)

array([ 5. , 47.5, 90. ])

In [29]:
np.linspace(25,125,5)

array([ 25.,  50.,  75., 100., 125.])

In [36]:
np.random.rand(3,3,3)

array([[[0.21466885, 0.25482138, 0.04408624],
        [0.92263789, 0.27007627, 0.22684237],
        [0.43005906, 0.26048566, 0.78481789]],

       [[0.35381309, 0.04337279, 0.90790355],
        [0.63893897, 0.63148751, 0.68907288],
        [0.73354852, 0.61954394, 0.2909879 ]],

       [[0.12522275, 0.36681093, 0.10608017],
        [0.25270496, 0.26393915, 0.93219448],
        [0.16475826, 0.83996563, 0.92251869]]])

In [38]:
np.random.randn(13)

array([-0.55237122,  0.49339936, -0.87409234, -0.41691225, -0.23529018,
        1.01790058, -1.3575872 , -0.29689561,  1.0655508 , -1.56379173,
       -0.74573398, -1.05742085, -1.76194998])

In [39]:
np.random.randn(3,3)

array([[-1.02768871, -1.99146367,  0.12838523],
       [-0.58421538, -0.39318866, -0.69080689],
       [ 0.3471266 , -0.63738083,  0.84929461]])

In [35]:
np.random.randint(3.5,34,80)

array([29, 20, 15,  3,  7,  7, 11, 21, 27, 10, 22, 11,  7, 30, 18,  6,  5,
        9, 21,  5, 31, 19, 10,  8, 22,  3, 25, 21, 16, 28, 16, 23, 27,  3,
       19, 22,  9, 23, 28, 18, 22, 26,  7, 17, 25, 10, 16, 16, 19, 18,  7,
        9, 25, 33, 28, 24, 15,  4, 27, 14, 15, 17, 19, 18, 17, 23, 30, 25,
       21, 29, 23, 11, 18,  4, 21, 26, 31, 28, 25,  4])

In [45]:
z = np.random.randint(3,34,size=(5,4))
z

array([[15, 23, 14,  5],
       [31,  7, 21, 13],
       [31,  3, 24, 23],
       [ 9, 27, 30,  8],
       [15, 19, 17, 11]])

In [42]:
z.shape

(5, 4)

In [46]:
z = z.reshape(4,5)
z

array([[15, 23, 14,  5, 31],
       [ 7, 21, 13, 31,  3],
       [24, 23,  9, 27, 30],
       [ 8, 15, 19, 17, 11]])

In [47]:
z = z.reshape(-1,4)
z

array([[15, 23, 14,  5],
       [31,  7, 21, 13],
       [31,  3, 24, 23],
       [ 9, 27, 30,  8],
       [15, 19, 17, 11]])

In [49]:
z = z.ravel()
z

array([15, 23, 14,  5, 31,  7, 21, 13, 31,  3, 24, 23,  9, 27, 30,  8, 15,
       19, 17, 11])

In [51]:
z.max


<function ndarray.max>

In [53]:
z.max()

31

In [54]:
z.argmax()

4

In [55]:
z.min()

3

In [57]:
z.argmin()

9

In [58]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)

In [59]:
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [61]:
my_arr1 = np.array([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)
my_arr1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [64]:
my_con = np.concatenate([my_arr,my_arr1],axis = 1)
my_con 

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [65]:
my_con[1,[2,3]]

array([5, 6])

In [66]:
my_con[[3,1],2]

array([9, 5])

In [67]:
my_con[0:2,1:3]

array([[1, 3],
       [3, 5]])

In [68]:
my_con[:,[0,3]]

array([[ 0,  4],
       [ 2,  6],
       [ 4,  8],
       [ 6, 10],
       [ 8, 12]])

#stacking

In [69]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])


In [70]:
a


array([[1, 2],
       [3, 4]])

In [71]:
b

array([[5, 6],
       [7, 8]])

In [73]:

x = np.stack((a,b))
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [76]:
x.shape

(2, 2, 2)

In [74]:
x.ndim

3

In [77]:
y= np.hstack((a,b))

In [78]:
y


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [79]:
y = np.vstack((a,b))

In [82]:
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [84]:
x.shape

(2, 2, 2)

In [85]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
array_1[array_1>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [88]:
array_1>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
array_1<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [90]:
array_1[array_1<5]

array([1, 2, 3, 4])

In [91]:
array_1[(array_1<10) & (array_1>3)]

array([4, 5, 6, 7, 8, 9])

In [94]:
array_1[(array_1<4) | (array_1>7)]

array([ 1,  2,  3,  8,  9, 10, 11, 12])

In [96]:
x**2

array([[[ 1,  4],
        [ 9, 16]],

       [[25, 36],
        [49, 64]]], dtype=int32)

In [97]:
np.power(x,2)

array([[[ 1,  4],
        [ 9, 16]],

       [[25, 36],
        [49, 64]]], dtype=int32)

In [98]:
np.log(x)

array([[[0.        , 0.69314718],
        [1.09861229, 1.38629436]],

       [[1.60943791, 1.79175947],
        [1.94591015, 2.07944154]]])

In [99]:
np.exp(x)

array([[[2.71828183e+00, 7.38905610e+00],
        [2.00855369e+01, 5.45981500e+01]],

       [[1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03]]])

In [100]:
np.sqrt(x)

array([[[1.        , 1.41421356],
        [1.73205081, 2.        ]],

       [[2.23606798, 2.44948974],
        [2.64575131, 2.82842712]]])

In [101]:
np.broadcast()

In [102]:
import pandas as pd

In [103]:
my_list

[1, 2, 3, 4, 5, 6, 7, 8]

In [104]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [106]:
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}

In [107]:
pd.Series(my_list,index=labels,)

X     5
y    10
z    15
h    20
dtype: int64

In [108]:
pd.Series(arr)

0     25
1     50
2     75
3    100
dtype: int32

In [109]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

In [110]:
ser = pd.Series([5,10,15,20,25,30], index = ['USA', 'Germany','France', 'UK','Turkey','Greece'])

In [111]:
ser

USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64

In [113]:
ser.sort_index()

France     15
Germany    10
Greece     30
Turkey     25
UK         20
USA         5
dtype: int64

In [114]:
ser.sort_values()

USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64

In [115]:
'Turkey' in ser

True

In [116]:
ser.isin([25])

USA        False
Germany    False
France     False
UK         False
Turkey      True
Greece     False
dtype: bool

In [117]:
ser.keys()

Index(['USA', 'Germany', 'France', 'UK', 'Turkey', 'Greece'], dtype='object')

In [120]:
ser.items

<bound method Series.items of USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64>

In [121]:
for key,value in ser.items():
    print(key,value)

USA 5
Germany 10
France 15
UK 20
Turkey 25
Greece 30


In [122]:
m = np.arange(1,30,2).reshape((3,5))
m

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [123]:
df = pd.DataFrame(m, columns= ['col1','col2','col3','col4','col5'])
df 

col1  col2  col3  col4  col5
0     1     3     5     7     9
1    11    13    15    17    19
2    21    23    25    27    29

In [125]:
df.head(1)

col1  col2  col3  col4  col5
0     1     3     5     7     9

In [127]:
df.tail(2)

col1  col2  col3  col4  col5
1    11    13    15    17    19
2    21    23    25    27    29

In [128]:
df.sample(2)

col1  col2  col3  col4  col5
1    11    13    15    17    19
2    21    23    25    27    29